name: Validate Pyinstaller Build

on:
  push:
    branches:
      - "pyinstaller_validate_gha"

jobs:
  build:
    name: build-pyinstaller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: chmod +x ./installer/pyinstaller/build-linux.sh
      - run: $USE_UBUNTU=1 ./installer/pyinstaller/build-linux.sh