name: Validate Pyinstaller Build

on:
  push:
    branches:
      - "py_installer_gha_ci"

jobs:
  build:
    name: build-pyinstaller
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: chmod +x ./installer/pyinstaller/build-linux.sh
      - run: CI_OVERRIDE=1 ./installer/pyinstaller/build-linux.sh aws-sam-cli-linux-x86_64.zip
      - uses: actions/upload-artifact@v3
        with:
          name: pyinstaller-zip
          path: .build/output/aws-sam-cli-linux-x86_64.zip